/Users/mario/.local/share/virtualenvs/lab3-5InpBgM6/bin/python: can't open file 'manage.py': [Errno 2] No such file or directory
